### ISSUE TITLE
Library isn't loading

### ISSUE THREAD

**Issue by MrAdrianPl** [CreativeDesigner3D/Library_Rooms#7]
This library isn't loading even with admin mode turned on.

**Comment by CreativeDesigner3D** [comment]
Sorry i didn't realize that i still had this repo open. I ended up consolidating several repos into the Home Builder Library. You can download the full package from here. https://creativedesigner3d.com/pyclone/

**Comment by MrAdrianPl** [comment]
Thanks for response Ive already downloaded home library ive just been thinking that this repo contains additional assets.
Also particle paint library and cad drawings library also arent loading.

**Comment by CreativeDesigner3D** [comment]
no these were early just repos used for testing. particle paint should work, but I don't think these are any assets included and I haven't tested it in awhile. I'll check it out in a bit and make any updates needed.
